name: app_factory

packages:
  - apps/*
  - packages/*

scripts:
  analyze:
    run: |
      melos exec -c 1 -- \
        "flutter analyze"
    description: Run analyze in all packages.

  test:
    run: |
      melos exec -c 1 -- \
        "flutter test"
    description: Run tests in all packages.

  clean:
    run: |
      melos exec -- \
        "flutter clean"
    description: Clean all packages.
